steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/repo/my-image', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/repo/my-image']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - -c
    - | 
       gcloud compute ssh bastion-host --zone us-west1-b 
       Y
       echo "$now"
       gcloud container clusters get-credentials primary --region us-west1 --project speedy-octane-346221
  # test 123