steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/repo1/my-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/repo1/my-image']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - -c
    - |
       gcloud compute ssh alert-testing --zone us-central1-a
       echo "Hello"
       gcloud container clusters get-credentials primary --region us-west1 --project speedy-octane-346221
       docker pull repo1/speedy-octane-346221/my-image
       docker run  repo1/speedy-octane-346221/my-image   
  # test 123